[package]
name = "syncprojects-fast"
version = "0.1.0"
edition = "2018"

[lib]
name = "syncprojects_fast"
crate-type = ["cdylib"]

[dependencies]
md-5 = "0.9.1"
bencher = "0.1.5"
rust-crypto = "0.2.36"
pyo3 = { version = "0.14.3", features = ["extension-module"] }